[project]
name = "mvp-tasia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "joblib>=1.5.2",
    "streamlit>=1.49.1",
    "xgboost>=3.0.5",
]
